### ISSUE TITLE
Langchain documentation bug - deprecated OpenAI model

### ISSUE THREAD

**Issue by RobSpectre** [browserbase/python-sdk#9]
In addition to #7 preventing [example 3](https://docs.browserbase.com/integrations/langchain/python) from working, the code references a deprecated OpenAImodel producing this error:

```
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
```

Was able to get it working swapping out that string, but prob want to update this example code to a currently supported model.

Thanks gang!

**Comment by kamath** [comment]
Hey! Appreciate you checking this out and apologize for the super delayed response here; we just unveiled [Stagehand](https://stagehand.dev) and we're coming out with a Python version too that's going to take the AI functionalities that were previously there to a whole new level :) In the meantime, we also [rewrote our Python SDK from the ground up](https://github.com/browserbase/sdk-python/tree/main) and would love for you to check it out!
